[package]
name = "bevy-raycast-test"
version = "0.1.0"
edition = "2021"

[dependencies]
# Math stuff
glam = "0.25.0"
# bevy = { version = "0.13.0", features = ["wayland"] }
png = "0.17.13"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
